apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: uber-clone 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: nginx-demo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uber-service
                port:
                  number: 80
